apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-app
  labels:
    app: dev-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
        - name: dev-app
          image: knoxuser/java-microservice
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dev-app
  name: dev-app-svc
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 8080
  selector:
    app: dev-app
  type: LoadBalancer
